name: Mutation testing CI
on: [ push, pull_request ]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    name: mutation testing PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        php: [ 8.3 ]
        symfony: [ 7.2.*' ]
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Infrastructure
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, flex
          coverage: xdebug2

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: "highest"

      - name: Load cache
        uses: actions/cache@v3
        with:
          path: var
          key: phpstan-result-cache-${{ matrix.php }}-${{ hashFiles('**/composer.lock', '**/.github') }}

      - run: XDEBUG_MODE=coverage ./vendor/bin/infection --threads=4 --show-mutations --only-covered
